### ISSUE TITLE
Login/Sign-up page

### ISSUE THREAD

**Issue by nbnw-org** [nbnworg/issue-repo#34]
### Description 
Need to create the login page as per the UI designed by Meghna . 

![Image](https://github.com/user-attachments/assets/9ceff96e-f577-4a6f-aea2-e531df6c9b3a)

Also look out for the the updates in the [https://www.figma.com/design/7LLn8THgUKytvdMtbna8nl/nbnw?node-id=818-2](url)

https://www.figma.com/design/7LLn8THgUKytvdMtbna8nl/nbnw?node-id=1506-197&t=ykWAdHrLstftMfD3-0

Note : this page also requires authentication in the backend 

### Requirements 
* login page created as per UI 
* functional login 

### Acceptance 
* reviewed by Meghna 
* reviewed by

**Comment by nbnw-org** [comment]
@SwanandBhuskute koi github pr repo banai? nbnworg mein... ni toh bana de... Thanks!

**Comment by SwanandBhuskute** [comment]
sir repo banayi hai , login ka frontend almost ho gaya hai, ab amplify dekhta hu

**Comment by SwanandBhuskute** [comment]
inital code push as per figma 
login/signup functionality - api + dynamodb table


![Image](https://github.com/user-attachments/assets/a1055dbb-5963-4842-93d1-a4c20bdb90b8)


![Image](https://github.com/user-attachments/assets/53c16be6-0562-424e-8919-50a42ec283fc)


![Image](https://github.com/user-attachments/assets/971afc84-b74a-4b73-9047-aa27f0247177)





_(code not arranged properly , api is exposed in page.tsx 's files, will separate the code later)_


### follow up
- add firstName, lastName to signup page after approving from meghna
- integrate "Continue with Google" similar option in signup page
- think on validation of email using some OTP service, so that fake emails can't get registered
- correct the forgot password working (PATCH request error)

**Comment by nbnw-org** [comment]
Any updates?

**Comment by nbnw-org** [comment]
https://github.com/nbnworg/nbnw-3p-eportal-frontend/pull/1
